 [build]
   command = "npm run lint && npm run typecheck && npm run build"
   publish = "dist"

 [build.environment]
   NODE_VERSION = "20"

 [context.staging.environment]
   VITE_BACKEND_URL = "https://keenvpnstaging.netlify.app/api"
